### PR TITLE
Fixed wallaby.js config

### PR DESCRIPTION
**Pull request by ArtemGovorov**
Wallaby doesn't support complex patterns, so I have simplified it a bit. Now all tests pass with wallaby.js.

### CODE REVIEW

**Comment by tommyminds** [comment]
Hey @ArtemGovorov. Thats strange! For me wallaby seems to be working fine with the complex pattern. But thanks for the tip!

**Comment by ArtemGovorov** [comment]
You are actually right, it does work in Atom, not in WebStorm though, so the simplified one works across all editors.

**Comment by tommyminds** [comment]
@ArtemGovorov Just out of curiosity, how did you find this repo and the fact that the tests were failing in WebStorm? ;)

**Comment by ArtemGovorov** [comment]
@TommyM I'm a creator of wallaby.js and occasionally search GitHub for repos with wallaby configs in them to see how people are using it, in order to get a better idea about what I can improve, what technologies people use with wallaby more, etc.

**Comment by tommyminds** [comment]
Alright, next-level support! Helping your users before they even realise they need help! :p Again, thanks for the PR. 

We are really excited about wallaby.js and are planning on starting to leverage it in all our projects.

**Comment by ArtemGovorov** [comment]
Heh, yes, kind of it :)
Awesome! You guys probably already know [where to find me](https://github.com/wallabyjs/public/issues) in case if I can help with any questions/issues regarding wallaby.

**Pull request merged**
